/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `user`;

CREATE TABLE `user` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` VARCHAR(127) NOT NULL,
  `nickname` VARCHAR(63) NULL,
  `passwd` VARCHAR(255) NULL,
  `avatar_id` VARCHAR(127) NULL,
  `email` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `user_id_i`
  ON `user` (`user_id`);

CREATE UNIQUE INDEX `nickname_i`
  ON `user` (`nickname`);

CREATE UNIQUE INDEX `email_i`
  ON `user` (`email`);

