/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `chat_session`;

CREATE TABLE `chat_session` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `session_id` VARCHAR(127) NOT NULL,
  `session_name` VARCHAR(127) NULL,
  `session_type` TINYINT NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `session_id_i`
  ON `chat_session` (`session_id`);

