/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `friend_relation`;

CREATE TABLE `friend_relation` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `user_id` VARCHAR(127) NOT NULL,
  `friend_id` VARCHAR(127) NOT NULL)
 ENGINE=InnoDB;

CREATE INDEX `user_id_i`
  ON `friend_relation` (`user_id`);

