/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `friend_event`;

CREATE TABLE `friend_event` (
  `id` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `event_id` VARCHAR(127) NOT NULL,
  `req_user_id` VARCHAR(127) NOT NULL,
  `rsp_user_id` VARCHAR(127) NOT NULL,
  `status` TINYINT NOT NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `event_id_i`
  ON `friend_event` (`event_id`);

