// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef MESSAGE_ODB_HXX
#define MESSAGE_ODB_HXX

#include <odb/version.hxx>

#if ODB_VERSION != 20500UL
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "message.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // msg_record
  //
  template <>
  struct class_traits< ::msg_record >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::msg_record >
  {
    public:
    typedef ::msg_record object_type;
    typedef ::msg_record* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef long unsigned int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // msg_record
  //
  template <typename A>
  struct query_columns< ::msg_record, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    id_type_;

    static const id_type_ id;

    // message_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    message_id_type_;

    static const message_id_type_ message_id;

    // created_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    created_time_type_;

    static const created_time_type_ created_time;

    // from_user_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    from_user_id_type_;

    static const from_user_id_type_ from_user_id;

    // to_session_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    to_session_id_type_;

    static const to_session_id_type_ to_session_id;

    // message_type
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        signed char,
        mysql::id_tiny >::query_type,
      mysql::id_tiny >
    message_type_type_;

    static const message_type_type_ message_type;

    // content
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    content_type_;

    static const content_type_ content;

    // file_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    file_id_type_;

    static const file_id_type_ file_id;

    // filename
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::basic_string< char >,
        mysql::id_string >::query_type,
      mysql::id_string >
    filename_type_;

    static const filename_type_ filename;

    // filesize
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        long unsigned int,
        mysql::id_ulonglong >::query_type,
      mysql::id_ulonglong >
    filesize_type_;

    static const filesize_type_ filesize;
  };

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::id_type_
  query_columns< ::msg_record, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::message_id_type_
  query_columns< ::msg_record, id_mysql, A >::
  message_id (A::table_name, "`message_id`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::created_time_type_
  query_columns< ::msg_record, id_mysql, A >::
  created_time (A::table_name, "`created_time`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::from_user_id_type_
  query_columns< ::msg_record, id_mysql, A >::
  from_user_id (A::table_name, "`from_user_id`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::to_session_id_type_
  query_columns< ::msg_record, id_mysql, A >::
  to_session_id (A::table_name, "`to_session_id`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::message_type_type_
  query_columns< ::msg_record, id_mysql, A >::
  message_type (A::table_name, "`message_type`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::content_type_
  query_columns< ::msg_record, id_mysql, A >::
  content (A::table_name, "`content`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::file_id_type_
  query_columns< ::msg_record, id_mysql, A >::
  file_id (A::table_name, "`file_id`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::filename_type_
  query_columns< ::msg_record, id_mysql, A >::
  filename (A::table_name, "`filename`", 0);

  template <typename A>
  const typename query_columns< ::msg_record, id_mysql, A >::filesize_type_
  query_columns< ::msg_record, id_mysql, A >::
  filesize (A::table_name, "`filesize`", 0);

  template <typename A>
  struct pointer_query_columns< ::msg_record, id_mysql, A >:
    query_columns< ::msg_record, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::msg_record, id_mysql >:
    public access::object_traits< ::msg_record >
  {
    public:
    struct id_image_type
    {
      unsigned long long id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // _id
      //
      unsigned long long _id_value;
      my_bool _id_null;

      // _message_id
      //
      details::buffer _message_id_value;
      unsigned long _message_id_size;
      my_bool _message_id_null;

      // _created_time
      //
      details::buffer _created_time_value;
      unsigned long _created_time_size;
      my_bool _created_time_null;

      // _from_user_id
      //
      details::buffer _from_user_id_value;
      unsigned long _from_user_id_size;
      my_bool _from_user_id_null;

      // _to_session_id
      //
      details::buffer _to_session_id_value;
      unsigned long _to_session_id_size;
      my_bool _to_session_id_null;

      // _message_type
      //
      signed char _message_type_value;
      my_bool _message_type_null;

      // _content
      //
      details::buffer _content_value;
      unsigned long _content_size;
      my_bool _content_null;

      // _file_id
      //
      details::buffer _file_id_value;
      unsigned long _file_id_size;
      my_bool _file_id_null;

      // _filename
      //
      details::buffer _filename_value;
      unsigned long _filename_size;
      my_bool _filename_null;

      // _filesize
      //
      unsigned long long _filesize_value;
      my_bool _filesize_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::msg_record, id_common >:
    public access::object_traits_impl< ::msg_record, id_mysql >
  {
  };

  // msg_record
  //
}

#include "message-odb.ixx"

#include <odb/post.hxx>

#endif // MESSAGE_ODB_HXX
