/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `msg_record`;

CREATE TABLE `msg_record` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `message_id` VARCHAR(127) NOT NULL,
  `created_time` VARCHAR(31) NOT NULL,
  `from_user_id` VARCHAR(127) NULL,
  `to_session_id` VARCHAR(127) NULL,
  `message_type` TINYINT NOT NULL,
  `content` TEXT NULL,
  `file_id` VARCHAR(127) NULL,
  `filename` VARCHAR(127) NULL,
  `filesize` BIGINT UNSIGNED NULL)
 ENGINE=InnoDB;

CREATE UNIQUE INDEX `message_id_i`
  ON `msg_record` (`message_id`);

